# -*- coding: utf-8 -*-
"""Hierarchical Cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJUgdRjlGUJsyOEpi6LzPcqcIztn28jM
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.cluster.hierarchy as shc
from sklearn.preprocessing import StandardScaler

data = pd.read_excel("IPL MATCH.xlsx")
data

data.shape

data.head()

X=data.drop(['Teams'],axis=1)

X

plt.figure(figsize=(10, 9))
plt.title("IPL 2024 Dendograms")
plt.xlabel("Teams")
plt.ylabel('Distance')
dend=shc.dendrogram(shc.linkage(X,method='centroid'))

from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters=6, linkage='average')
clt1=cluster.fit_predict(X)

clt1
